import Link from "next/link";
import { BookOpen, Home, Layers3, LibraryBig } from "lucide-react";
import { deleteBookshelfAction, updateBookshelfAction } from "@/app/actions";
import { LocationForm } from "@/components/location-form";
import { ShelfGrid } from "@/components/shelf-grid";
import { Card, EmptyState, PageHeader } from "@/components/ui";
import { ConfirmSubmitButton } from "@/components/confirm-submit-button";
import { getBookshelfDefinitions, getCopiesAtLocation, getHouseLevels, getHouseMap, getLocations, getRooms } from "@/lib/data";

export const dynamic = "force-dynamic";

export default async function LocationsPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | undefined>>;
}) {
  const params = await searchParams;
  const selectedId = params.location ? Number(params.location) : undefined;
  const [locations, houseMap, levels, rooms, bookshelfDefinitions, copies] = await Promise.all([
    getLocations(),
    getHouseMap(),
    getHouseLevels(),
    getRooms(),
    getBookshelfDefinitions(),
    selectedId ? getCopiesAtLocation(selectedId) : Promise.resolve([]),
  ]);
  const selectedLocation = locations.find((location) => location.id === selectedId);

  return (
    <>
      <PageHeader eyebrow="Locations" title="Browse your little house">
        <Link className="btn-secondary" href="/catalog">Search catalog</Link>
      </PageHeader>

      <section className="grid gap-6 lg:grid-cols-[0.82fr_1.18fr]">
        <div className="space-y-6 lg:sticky lg:top-6 lg:self-start">
          <Card>
            <p className="text-xs font-bold uppercase tracking-wider text-[#8f5f3f]">Build the house</p>
            <h2 className="mt-2 font-serif text-2xl font-bold">Add rooms and bookcases</h2>
            <div className="mt-4">
              <LocationForm levels={levels} rooms={rooms} bookshelfDefinitions={bookshelfDefinitions} />
            </div>
          </Card>

          {selectedId ? (
            <Card className="border-[#5e7d50]/30 bg-[#fffaf0]/95 shadow-[#5e7d50]/10">
              <p className="text-xs font-bold uppercase tracking-wider text-[#5e7d50]">Selected shelf spot</p>
              <h2 className="mt-2 font-serif text-2xl font-bold">What lives here?</h2>
              {selectedLocation ? (
                <div className="mt-4 rounded-2xl bg-[#f3dfbd]/50 p-4">
                  <LocationForm location={selectedLocation} />
                </div>
              ) : null}
              {copies.length ? (
                <div className="mt-4 grid gap-3">
                  {copies.map(({ book, copy }) => (
                    <Link href={`/books/${book.id}`} className="rounded-2xl bg-white/60 p-4 transition hover:bg-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#5e7d50]" key={copy.id}>
                      <strong>{book.title}</strong>
                      <p className="text-sm text-[#704b38]">Copy #{copy.copyNumber} · {copy.status}</p>
                    </Link>
                  ))}
                </div>
              ) : (
                <div className="mt-4"><EmptyState title="No books in this spot." /></div>
              )}
              <p className="mt-5 rounded-2xl bg-[#fffaf0]/70 p-3 text-sm font-bold text-[#704b38]">
                Shelf spots are generated by the bookcase size. To remove this spot, resize or delete the bookcase.
              </p>
            </Card>
          ) : null}
        </div>

        <Card className="relative overflow-hidden">
          <div className="absolute right-8 top-8 h-28 w-28 rounded-[2rem] bg-[#dca36b]/20 blur-sm" />
          <div className="relative flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
            <div>
              <p className="text-xs font-black uppercase tracking-[0.26em] text-[#8f5f3f]">House map</p>
              <h2 className="mt-2 font-serif text-3xl font-bold">Clickable shelf browser</h2>
            </div>
            <div className="rounded-full bg-[#5e7d50]/10 px-4 py-2 text-sm font-black text-[#5e7d50]">Front / back depth ready</div>
          </div>

          {locations.length ? (
            <div className="relative mt-6 space-y-6">
              {houseMap.map(({ level, rooms: levelRooms }) => (
                <section key={level.id} className="rounded-[2rem] border border-[#d2ad84]/50 bg-[#fffaf0]/65 p-4 shadow-inner shadow-[#8f5f3f]/5">
                  <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                    <div className="flex items-center gap-3">
                      <span className="rounded-2xl bg-[#dca36b]/25 p-3 text-[#704b38]"><Home size={24} /></span>
                      <div>
                        <h3 className="font-serif text-3xl font-bold">{level.name}</h3>
                        <p className="text-sm font-bold text-[#704b38]">{levelRooms.length} rooms · {levelRooms.reduce((sum, room) => sum + room.bookshelves.length, 0)} bookcases</p>
                      </div>
                    </div>
                  </div>

                  <div className="mt-4 grid gap-4">
                    {levelRooms.map(({ room, bookshelves }) => (
                      <article key={room.id} className="rounded-[1.5rem] bg-white/55 p-4">
                        <div className="mb-4 flex items-center gap-2 text-[#704b38]"><Layers3 size={18} /><h4 className="font-serif text-2xl font-bold text-[#44291f]">{room.name}</h4></div>
                        <div className="grid gap-4 xl:grid-cols-2">
                          {bookshelves.map(({ bookshelf, locations: shelfLocations, copyCount }) => (
                            <div key={bookshelf.id} className="rounded-[1.35rem] border border-[#d2ad84]/50 bg-[#f9edd6]/75 p-4">
                              <div className="mb-4 flex items-start justify-between gap-3">
                                <div>
                                  <div className="flex items-center gap-2"><LibraryBig size={18} className="text-[#8f5f3f]" /><h5 className="font-bold">{bookshelf.name}</h5></div>
                                  <p className="mt-1 text-xs font-bold uppercase tracking-widest text-[#8f6b52]">{bookshelf.rowCount} rows · {bookshelf.depthCount} deep</p>
                                </div>
                                <span className="rounded-full bg-[#5e7d50]/10 px-3 py-1 text-xs font-black text-[#5e7d50]"><BookOpen size={13} className="mr-1 inline" />{copyCount}</span>
                              </div>
                              <ShelfGrid locations={shelfLocations} selectedId={selectedId} />
                              <details className="bookcase-details mt-4 rounded-2xl border border-[#d2ad84]/50 bg-white/55 p-3">
                                <summary className="flex cursor-pointer list-none items-center justify-between text-sm font-bold uppercase tracking-wider text-[#704b38]">
                                  <span>Edit bookcase</span>
                                  <span className="bookcase-details-chevron text-lg leading-none">⌄</span>
                                </summary>
                                <form action={updateBookshelfAction.bind(null, bookshelf.id)} className="mt-3 grid gap-3 md:grid-cols-2">
                                  <label className="field-label">
                                    <span>Preset link</span>
                                    <select className="field-input" name="definitionId" defaultValue={bookshelf.definitionId ?? ""}>
                                      <option value="">Custom size</option>
                                      {bookshelfDefinitions.map((definition) => (
                                        <option key={definition.id} value={definition.id}>
                                          {definition.name} ({definition.rowCount} rows · {definition.depthCount} deep)
                                        </option>
                                      ))}
                                    </select>
                                  </label>
                                  <label className="field-label">
                                    <span>Name *</span>
                                    <input className="field-input" name="name" required defaultValue={bookshelf.name} />
                                  </label>
                                  <label className="field-label">
                                    <span>Rows *</span>
                                    <input className="field-input" name="rowCount" type="number" min={1} required defaultValue={bookshelf.rowCount} />
                                  </label>
                                  <label className="field-label">
                                    <span>Depths *</span>
                                    <input className="field-input" name="depthCount" type="number" min={1} max={2} required defaultValue={bookshelf.depthCount} />
                                  </label>
                                  <label className="field-label md:col-span-2">
                                    <span>Notes</span>
                                    <textarea className="field-input min-h-20" name="notes" defaultValue={bookshelf.notes ?? ""} />
                                  </label>
                                  <div className="flex flex-wrap gap-2 md:col-span-2">
                                    <button className="btn-primary">Save bookcase</button>
                                  </div>
                                </form>
                                <form action={deleteBookshelfAction.bind(null, bookshelf.id)} className="mt-3">
                                  <ConfirmSubmitButton message="Delete this whole bookcase and all empty shelf spots? This fails if books still use any spot.">Delete bookcase</ConfirmSubmitButton>
                                </form>
                              </details>
                            </div>
                          ))}
                        </div>
                      </article>
                    ))}
                  </div>
                </section>
              ))}
            </div>
          ) : (
            <EmptyState title="No house shelves yet.">The app seeds Downstairs and Upstairs automatically for fresh databases.</EmptyState>
          )}
        </Card>
      </section>

    </>
  );
}
